config/routes.rb
Rails.application.routes.draw do
  #get 'articulos/new'
  get 'articulos/index'

  #con esto creamos todas las rutas del recurso articulo directamente
  resources :articulos 

  get 'estaticas/contacto'
  get 'estaticas/nosotros'
  
  get 'home/index'
  #aqui le estamos indicando que la raiz es el controler home y la vista index
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articulos_controller.rb
class ArticulosController < ApplicationController
  
  def index
  end
  
  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def show
  end

  def destroy
  end

end

app/controllers/estaticas_controller.rb
class EstaticasController < ApplicationController
  def contacto
    @id = params[:id]
    @pag = params[:pagina]
  end

  def nosotros
    @mensaje = "Bienvenidos a tod@s de nuevo a mi blog!"
    @usuarios = ['Miryam', 'Sergio', 'Oliver', "Luca"]
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articulos_helper.rb
module ArticulosHelper
end

app/helpers/estaticas_helper.rb
module EstaticasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articulos/edit.html.erb
<h1>Articulos#index</h1>
<p>Find me in app/views/articulos/index.html.erb</p>

app/views/articulos/index.html.erb
<h1>Articulos#index</h1>
<p>Find me in app/views/articulos/index.html.erb</p>

app/views/articulos/new.html.erb
<h1>Articulos#new</h1>
<p>Find me in app/views/articulos/new.html.erb</p>

app/views/articulos/show.html.erb
<h1>Articulos#index</h1>
<p>Find me in app/views/articulos/index.html.erb</p>

app/views/estaticas/contacto.html.erb
<%= provide(:titulo, "Contacto")%>
<p>Aquí puedes contactar con nosotros</p>

<% #params.inspect  %>

<br>

<p>ID: <%= @id %></p>
<p>PAG: <%= @pagina %></p>

<%= content_for(:saludo, "Hola")  %>
<%= yield :saludo %>

app/views/estaticas/nosotros.html.erb
<%= provide(:titulo, "Nosotros")%>
<p>Aquí podrás saber un poco sobre nosotros</p>

<%= @mensaje %>
<br>

<ul>
    <%= @usuarios.each do |i| %>
        <%= "<li> #{i} </li>".html_safe %>
    <% end %>
</ul>


<%= link_to 'Home', root_path %>
<%= link_to 'Contacto', estaticas_contacto_path %>

<br>

app/views/home/index.html.erb
<%= provide(:titulo, "Mi Blog")%>
<p>Bienvenidos a mi Blog!</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:titulo)%></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%# aqui ponemos el parcial %>
  <%= render 'shared/header'%>
  <%# yield muestra el contenido de cada vista en concreto %>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'Contacto', estaticas_contacto_path %>
<%= link_to 'Nosotros', estaticas_nosotros_path %>